### ISSUE TITLE
ENCODE option --outFilterMismatchNoverLmax not being displayed in the manual

### ISSUE THREAD

**Issue by biounix** [alexdobin/STAR#267] opened 2017-05-23 16:54 UTC
In section 3.2.2 of the manual (ENCODE options, beginning of page 8), option `--outFilterMismatchNoverLmax` is missing because line 206 in STARmanual.tex is commented. In older versions of the manual this option was correctly displayed.

In addition, value 0.06 in the formula of the description should be corrected to 0.04.

Thanks.

**Comment by DarioS** [comment] 2017-05-30 02:00
Duplicate of issue #265.

**Closed** 2019-08-23 19:59 UTC
