### ISSUE TITLE
STAR with Adapters

### ISSUE THREAD

**Issue by annaquaglieri16** [alexdobin/STAR#232] opened 2017-01-25 05:05 UTC
Hi Alex, 

I would like to better understand how STAR deals with adapter. Before trimming adapters and using the following parameters:
STAR \
	--genomeDir $genome \
	--readFilesIn ${FQ1} ${FQ2} \
	--readFilesCommand zcat \
	--runThreadN $(nproc) \
	--outFilterType BySJout \
	--outFilterMultimapNmax 15 \
	--alignSJoverhangMin 8 \
	--outBAMcompression 10 \
	--alignSJDBoverhangMin 1 \
	--limitBAMsortRAM 84033479973 \
	--outFilterMismatchNmax 999 \
	--alignIntronMin 20 \
	--alignIntronMax 200000 \
	--alignMatesGapMax 200000 \
	--outFileNamePrefix ${outdir}/${sampleout} \
	--outSAMtype BAM SortedByCoordinate 

I was getting a consistently  higher % of unmapped reads too short for libraries with 125bp compared to 100 bp (different runs from the same sample). I was also loosing short fragments, as you can see from the steep drop around the 100bp and 125bp length:

![screen shot 2017-01-25 at 2 09 03 pm](https://cloud.githubusercontent.com/assets/7087258/22278388/486c99a6-e317-11e6-9af7-f41fa3d0b43d.png)

 After removing adapters with trimmomatic (minimum of 8bp adapter length) I get imporved QC and % of reads mapped from both libraries (100bp and 125bp) but a steep drop in the fragemnt size distribution few bases before the read length:

![screen shot 2017-01-25 at 4 00 45 pm](https://cloud.githubusercontent.com/assets/7087258/22278411/7edb9352-e317-11e6-8aeb-c2901fc81ff7.png)

Do you have an idea for this drop? 
Also, is it correct that STAR with those parameters will only output properly paired reads that are within a alignMatesGapMax distance between each other? If only one of the two mates does not map or they are to distant, they won't be in the final aligned BAM file (unless chimeric option specified). 

Thanks a lot for your help, 
Anna

**Comment by alexdobin** [comment] 2017-01-27 22:01
Hi Anna,

this is an interesting observation. Is the width of the drop close to 8b - it seems so? Since Trimmomatic only trims >8b of the adapter, the shorter adapters will be untrimmed and follow the drop at the read length of your initial plot. After trimming kicks in, the alignments are recovered.
If you make trimmomatic trim more aggressively (down to 1 adapter base) it will hopefully close this gap.

I am somewhat concerned about such a significant drop in the insert size at the read length in the no-trimming case. I will see if I can reproduce this problem in my test runs.

Cheers
Alex

**Comment by annaquaglieri16** [comment] 2017-01-30 02:54
Hi Alex, 
Thanks for your answer. 
the width of the drop in the second plot (trimmed reads) is between 1-6 bp. My initial plot was untrimmed. Therefore, I think that the drop in the first plot is simply due to the fact that STAR soft clip adapters and the remaining fragment length might not pass the 0.66 * fragment default threshold. 

The second plot shows the distribution of the fragment sizes (collected by picardtools) after aligning the trimmed reads. What I noticed from IGV is the situation below. A read pair with completely overlapping mates has 2bp adapter bases at each end. In this case STAR reports an ISIZE = 0, and I am not sure if it is because micro homology between the adapter and the actual sequence. 

Here is what I see in IGV for such read : 
![screen shot 2017-01-30 at 1 47 48 pm](https://cloud.githubusercontent.com/assets/7087258/22410998/10f43a9e-e6f3-11e6-89c9-b1506d281cba.png)

This read pair with 2bp adapter on each end (both pairs are shown one below the other one) has ISIZE = 0 and I reckon this is one of the situations creating the drop. 

Best wishes, 

Anna

**Comment by alexdobin** [comment] 2017-01-31 21:49
Hi Anna,

regarding your last example, STAR is not supposed to return ISIZE=0 in this case - could you please grep this read from the SAM file and send it to me?

The min matched bases filter will be triggered if the map fully overlap, the insert size is 83b, and 42b are clipped from each end. The number of matched bases is then 83*2=166~0.66*250 . This can be seen on your first plot as the point where the number of fragments goes to almost zero. However, the sharp drop happens at the 125b = read length.

Cheers
Alex

**Comment by annaquaglieri16** [comment] 2017-02-01 00:46
Hi Alex, 

here is the read:

grep 700666F:233:CAH6NANXX:7:2106:4215:55388  59_CAH6NANXX_L007Aligned.sortedByCoord.out.sam

700666F:233:CAH6NANXX:7:2106:4215:55388 145     chr16   67118841        255     2S123M  =       67118842        0       TCTCTCATATGGTCATTGTGAGGATTAAATGAGTAAATACATGTGAAACCACTTTTAGCGTATGTGCCACTGACTAGGTGTCAGGTGCTATTATTATTGTTAATATTATTTAAAGTATTACATAA   GFGGGGGEGGGGGGGGDFFDC0GEGGGGGGGFEGGGGGGGGGCGFF@0GEGGGGGGGDGGGGFGFGGGGGGGGDGGGGGGGGGGGGGGGGEGGGGGGGGEGGGGGGGGEGFCCEGEGGGGBBBCC   NH:i:1  HI:i:1  AS:i:121        nM:i:0  NM:i:0
700666F:233:CAH6NANXX:7:2106:4215:55388 97      chr16   67118842        255     123M2S  =       67118841        0       CTCATATGGTCATTGTGAGGATTAAATGAGTAAATACATGTGAAACCACTTTTAGCGTATGTGCCACTGACTAGGTGTCAGGTGCTATTATTATTGTTAATATTATTTAAAGTATTACATAAAGA   3>:@AEFGGFGGGGGGGGGGFGGGFCFGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFG1EBFGGGGGGGGGGDDFGGGGGDCGGGE0:FFGEGGGGGGGFGFGGFGGGEGGGGGGGG   NH:i:1  HI:i:1  AS:i:121        nM:i:0  NM:i:0

Cheers,
Anna

**Comment by alexdobin** [comment] 2017-02-10 17:47
Hi Anna,

what parameters are you using for mapping? This read does not map with default parameters to h37.

Cheers
Alex

**Comment by annaquaglieri16** [comment] 2017-02-12 01:05
Hi Alex, below are the parameters that I used to map to hg19:

STAR \
--genomeDir $genome \
--readFilesIn ${FQ1} ${FQ2} \
--readFilesCommand zcat \
--runThreadN $(nproc) \
--outFilterType BySJout \
--outFilterMultimapNmax 15 \
--alignSJoverhangMin 8 \
--outBAMcompression 10 \
--alignSJDBoverhangMin 1 \
--outFilterMismatchNmax 999 \
--alignIntronMin 20 \
--outReadsUnmapped Fastx \
--chimSegmentMin 10 \
--chimSegmentReadGapMax 6 \
--chimOutType WithinBAM \
--alignIntronMax 200000 \
--alignMatesGapMax 200000 \
--outFileNamePrefix ${outdir}/${sampleout} \
--outSAMtype BAM SortedByCoordinate


Cheers,
Anna


2017-02-11 4:47 GMT+11:00 alexdobin <notifications@github.com>:

**Comment by alexdobin** [comment] 2017-02-14 21:39
Hi Anna,

thanks for the parameters, sorry I missed that you already listed them in the first post.
STAR considers this read to be chimeric, because the 5' of the mate on the + strand is downstream of the 5' of the mate on the - strand, which is not allowed for normal alignments, and for chimeric alignments, the insert size is always 0. From the insert size distribution, it does not look like you have a lot of such reads. It's also unlikely that they affect the dip at the read length. I am still looking for this effect in may data.

Cheers
Alex

**Closed** 2019-08-05 16:42 UTC
