### ISSUE TITLE
different motifs for the same junction while collapsing junctions

### ISSUE THREAD

**Issue by Lucas-Maciel** [alexdobin/STAR#509] opened 2018-10-23 17:13 UTC
Hello,

I installed star with the following commands

RUN wget https://github.com/alexdobin/STAR/archive/2.6.0a.tar.gz && tar -xzf 2.6.0a.tar.gz && mv ${HOME}/bin/STAR-2.6.0a/bin/Linux_x86_64/STAR ${HOME}/bin/STAR-2.6.0a/bin/Linux_x86_64/star

And I was running STAR with 800 libraries a few of them presented the following error:
EXITING becaues of BUG: different motifs for the same junction while collapsing junctions
SM_V7_1 12388872 12390607 1 0 1 -3

What should I do?

**Comment by alexdobin** [comment] 2018-10-23 21:51
Hi Lucas,

2.6.0a version was buggy (marked as pre-release) and replaced with 2.6.0c.
Please try the 2.6.1c as the most stable version for the cases this error occurred, also re-generate the genome with this version.

If the problem is not fixed, I will need the fastq files and the genome fasta/gtf to track the problem. I had accidental reports of this problem but was never able to trace it, as it always disappeared after proper genome indexing.

Cheers
Alex

**Comment by Lucas-Maciel** [comment] 2018-10-24 00:56
As I said I have already run 800 libraries. I'm going to do this in two pass mode, so now I have to regenerate the genome. Is possible to regenerate the genome with the output from the 2.6.0 using the 2.6.1? Or is there any incompatibility between the outputs that will be used to regenerate?

Thank you

**Comment by alexdobin** [comment] 2018-10-24 15:40
Hi Lucas,

you can use the 1st pass output (i.e. SJ.out.tab files) from the 2.6.0 runs that did not fail, generate the 2nd pass genome index and map with 2.6.1. Note that if you are collecting junctions from so many samples, you may want to heavily filter them - otherwise your 2nd pass mapping speed and unique mapping rates may be reduced.
And I would recommend re-mapping the failed libraries with 2.6.1 - to make sure that it will work, and also to get the extra SJ.out.tab files.

Cheers
Alex

**Comment by Lucas-Maciel** [comment] 2018-10-24 19:09
Hi alex,

Yes, I'm going to filter my junctions in order to get a good result.

I installed the 2.6.1c but now I'm having problems to generate the genome index:
~/data/output/star_alignment# nice -n 0 star --runThreadN 16 --runMode genomeGenerate --genomeDir /home/snape/data/output/star_alignment/star_dir --genomeF
astaFiles /home/snape/data/Smansoni_v7.fa --sjdbGTFfile /home/snape/data/v7.gtf --sjdbOverhang -1
Oct 24 19:01:41 ..... started STAR run
Oct 24 19:01:41 ... starting to generate Genome files
Oct 24 19:01:52 ... starting to sort Suffix Array. This may take a long time...
Oct 24 19:01:56 ... sorting Suffix Array chunks and saving them to disk...
Oct 24 19:04:00 ... loading chunks from disk, packing SA...
Segmentation fault (core dumped)

This didn't happen in the other version.

**Comment by alexdobin** [comment] 2018-10-25 13:49
Hi Lucas,

you have --sjdbOverhang -1 which is not allowed, you have to specify a positive value, close to your read length, or do not specify it at all to keep the default 100.
If this does not solve the problem, please send me the Log.out file.

Cheers
Alex

**Closed** 2019-09-02 21:40 UTC
Labels: issue, resolved
