### ISSUE TITLE
--quantMode GeneCounts gives different counts with HTSeq count

### ISSUE THREAD

**Issue by nuan604** [alexdobin/STAR#974] opened 2020-07-23 05:54 UTC
Hi,

The STAR is such a good tool to do the alignment, and I really like it. Recently, I used the --quantMode GeneCounts to get the count table, but I found it is differnt from the htseq-count result. So I wonder if I could get the default of  --quantMode GeneCounts for htseq to find what happened to my data. Thanks so much.

This is the code of mine:

STAR --runThreadN 10 --genomeDir /anno/star/star_index_mm10 --readFilesCommand zcat --readFilesIn /RNA-seq/trim_adaptor/L3_370370.R1_val_1.fq.gz /RNA-seq/trim_adaptor/L3_370370.R2_val_2.fq.gz --outFileNamePrefix Sample1_  --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts

htseq-count -f bam -s reverse /RNA-seq/trim_adaptor_star/Sample1_Aligned.sortedByCoord.out.bam /anno/star/Mus_musculus/UCSC/mm10/Annotation/Archives/archive-current/Genes/genes.gtf  > C1-18-TdEPS-1_r.count

 In the ReadsPerGene.out.tab file, the column 4 is for counts for the 2nd read strand aligned with RNA (htseq-count option -s reverse).but the count number is different. I wonder why and which one I should use for the next step. 

Hope to get your help!

Thanks!

**Comment by alexdobin** [comment] 2020-07-25 17:18
Hi @nuan604 

are you using the same in htseq-count as you used for generating the STAR index?
If so, the counts should agree exactly. Can you create a small example for me?
You can run STAR with `--readMapNumber 100000`, and then run htseq-count on it, and compare the counts.
If the counts are not different, you would need to increase `--readMapNumber` until the become different.
Then, please send me the BAM file, Log.out, ReadsPerGene, and htseq-count output.

Thanks!
Alex

**Comment by EngineerReversed** [comment] 2020-09-27 16:20
I am currently using [Biowdl RNA-Seq](https://github.com/biowdl/RNA-seq) pipeline.
I am getting different results for `STAR --quantMode GeneCounts` and `htseq-count union mode`. I also tried with other modes of htseq-count to see if there were any similarities but didn't get any success.

*PS:* Scroll right to see all the options

  | star | htseq-count(mode=union) | htseq-count(mode=intersection-strict) | htseq-count(mode=intersection-nonempty) | htseq-count(mode=union and non-unique all) | htseq-count(mode=union and non-unique none)
-- | -- | -- | -- | -- | -- | --
g_1 | 2371 | 2315 | 2281 | 2315 | 2317 | 2315
g_2 | 381 | 407 | 899 | 1121 | 1808 | 407
g_3 | 741 | 761 | 1148 | 1356 | 2161 | 761
g_4 | 2361 | 2283 | 1813 | 2283 | 2286 | 2283
g_5 | 382 | 393 | 913 | 1109 | 1863 | 393
g_6 | 706 | 698 | 960 | 1373 | 2170 | 698
__no_feature | 0 | 0 | 1586 | 5 | 0 | 0
__ambiguous | 2995 | 2873 | 130 | 168 | 2873 | 2873
__too_low_aQual | 0 | 0 | 0 | 0 | 267 | 0
__not_aligned | 5 | 5 | 5 | 5 | 5 | 5
__alignment_not_unique | 60 | 267 | 267 | 267 | 267 | 267

**Comment by EngineerReversed** [comment] 2020-09-27 16:22
Also, is there going to be any release towards counting multi-mappers in gene to read counting like htseq?

**Comment by alexdobin** [comment] 2020-09-28 22:41
Hi Abhishek,

what strandedness option you are using with htseq-count, and which column in ReadPerGene file you are comparing it to?

Cheers
Alex

**Comment by EngineerReversed** [comment] 2020-09-30 14:59
Hi Alex,

My reads are unstranded and I am using the second column in `ReadPerGene` file.

**Comment by alexdobin** [comment] 2020-09-30 22:03
Hi Abhishek,

and what strandedness option did you use for htseq-count? What are the gene strands in the GTF file?

Also, another strange thing is that there are 60 multimappers in STAR output, and 267 in htseq-count.

Cheers
Alex

**Comment by EngineerReversed** [comment] 2020-10-01 05:09
I used `-s no` parameter in htseq-count. The data is artificially prepared in [Biowdl pipeline](https://biowdl.github.io/RNA-seq/) for easy testing.  There are 6 gene strands(g1 to g6) in [GTF file](https://github.com/biowdl/RNA-seq/blob/develop/tests/data/reference/reference.gtf).

**Comment by alexdobin** [comment] 2020-10-01 14:55
Hi Abhishek,


GTF seems to be in order, so I need to try to reproduce the issue myself.
Could you send me the FASTA, GTF, and read FASTQs for this example?

Thanks!
Alex

**Comment by EngineerReversed** [comment] 2020-10-01 17:52
Sure, here are the files which you requested for:
* [GTF](https://github.com/biowdl/RNA-seq/blob/develop/tests/data/reference/reference.gtf)
* [FASTA](https://github.com/biowdl/RNA-seq/blob/develop/tests/data/reference/reference.fasta)
* [FASTQ R1](https://github.com/biowdl/RNA-seq/blob/develop/tests/data/rna3/R1.fq.gz)
* [FASTQ R2](https://github.com/biowdl/RNA-seq/blob/develop/tests/data/rna3/R2.fq.gz)

The other reference files are in [reference](https://github.com/biowdl/RNA-seq/tree/develop/tests/data/reference) folder.

**Comment by alexdobin** [comment] 2020-10-02 16:24
Hi Abhishek:

I am getting an exact agreement between STAR 2.7.5c and htseq-count (latest) for this test example. Here is what I did:
```
htseq-count -s no Aligned.out.bam GenomeDir/reference.gtf
[E::idx_find_and_load] Could not retrieve index file for 'Aligned.out.bam'
38 GFF lines processed.
[E::idx_find_and_load] Could not retrieve index file for 'Aligned.out.bam'
9997 alignment pairs processed.
g_1     2371
g_2     381
g_3     741
g_4     2361
g_5     382
g_6     706
__no_feature    0
__ambiguous     2995
__too_low_aQual 0
__not_aligned   0
__alignment_not_unique  60

STAR --runMode genomeGenerate --genomeDir ./ --genomeFastaFiles reference.fasta --sjdbGTFfile reference.gtf --genomeSAindexNbases 6

STAR --readFilesIn R1.fq.gz R2.fq.gz --outSAMtype BAM Unsorted --readFilesCommand zcat --quantMode GeneCounts

cat ReadsPerGene.out.tab
N_unmapped      5       5       5
N_multimapping  60      60      60
N_noFeature     0       3487    3455
N_ambiguous     2995    0       0
g_1     2371    1164    1208
g_2     381     923     941
g_3     741     1108    1115
g_4     2361    1202    1159
g_5     382     984     910
g_6     706     1069    1149
```

Note that my STAR results agree with your STAR results, so you may have a problem with the htseq-count run.

Cheers
Alex

**Comment by EngineerReversed** [comment] 2020-10-05 07:10
Hi Alex, 

Our `STAR` results are similar. However, there is a difference in `htseq-count` results. I am not sure if it is due to the version difference or parameter differences. 

`STAR` command: 
>STAR \
>--readFilesIn /cromwell-executions/RNAseq/54d3e144-fee4-4e49-bcef-e77e2717ac3f/call-sampleJobs/shard-0/SampleWorkflow/5bb1a2dd-462f-470a-bece-6977753e2f58/call-star/shard-0/inputs/266530435/cutadapt_R1.fq.gz /cromwell-executions/RNAseq/54d3e144-fee4-4e49-bcef-e77e2717ac3f/call-sampleJobs/shard-0/SampleWorkflow/5bb1a2dd-462f-470a-bece-6977753e2f58/call-star/shard-0/inputs/266530435/cutadapt_R2.fq.gz \
>--outFileNamePrefix ./samples/rna3-paired-end/lib_lib1--rg_rg1/rna3-paired-end-lib1-rg1.star. \
>--genomeDir /cromwell-executions/RNAseq/54d3e144-fee4-4e49-bcef-e77e2717ac3f/call-sampleJobs/shard-0/SampleWorkflow/5bb1a2dd-462f-470a-bece-6977753e2f58/call-star/shard-0/inputs/1196344010/ \
>--outSAMtype BAM SortedByCoordinate \
>--readFilesCommand zcat \
>--outSAMunmapped Within KeepPairs \
>--runThreadN 4 \
>--twopassMode Basic \
>--outSAMattrRGline  "ID:rg1" "LB:lib1" "PL:illumina" "SM:rna3-paired-end"

`htseq-count` command:
>htseq-count \
>-f bam \
>-r pos \
>-s no \
>/cromwell-executions/RNAseq/54d3e144-fee4-4e49-bcef-e77e2717ac3f/call-expression/MultiBamExpressionQuantification/6e0bb05f-351a-4ff0-a6a0-1d716008f507/call-htSeqCount/shard-0/inputs/720857976/rna3-paired-end.markdup.bam \
>/cromwell-executions/RNAseq/54d3e144-fee4-4e49-bcef-e77e2717ac3f/call-expression/MultiBamExpressionQuantification/6e0bb05f-351a-4ff0-a6a0-1d716008f507/call-htSeqCount/shard-0/inputs/253336215/reference.gtf \

Tool versions: 
* `STAR`=**2.7.5c**
* `htseq`=**0.11.0**

I have bam files sorted by coordinate for downstream analysis. Is that the reason for differences in results?

**Comment by alexdobin** [comment] 2020-10-15 00:26
Hi Abhishek,

I have a feeling there is some kind of problem with htseq-count using the coordinate-sorted BAM files with -r pos option.
You can try to run it on the unsorted file without this option, and hopefully, you will reproduce the correct counts.

Cheers
Alex

Cheers
Alex

**Comment by EngineerReversed** [comment] 2020-10-15 06:51
Hi Alex,

I have raised an issue on `htseq` repository for clarification.

**Comment by iosonofabio** [comment] 2020-12-26 00:22
Thanks @alexdobin 

htseq-count has been undergoing some amount of changes over the last few years but one thing that I didn't have time to fix was such rarely but consistently reported bugs with coordinate sorted files. Alas, not a single user could be bothered sending over decent BAM and GTF files and the expected output of htseq for such a case. Hope I can get that fixed here.

**Comment by iosonofabio** [comment] 2020-12-26 04:01
I have run a test on this one and find that all workflows agree:

1. `STAR --quantMode GeneCounts`, first column (i.e. unstranded)
2. `htseq-count -s no Aligned.out.bam` (i.e. unstranded on the unsorted BAM file from STAR)
3. `samtools sort -o Aligned.out.sorted.bam Aligned.out.bam && htseq-count -r pos -s no Aligned.out.sorted.bam` (i.e. first sort the BAM file via samtools, then run htseq unstranded on the sorted file)
4. `STAR --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts`, first column (i.e. unstranded, after sorting by STAR)
5. `STAR --outSAMtype BAM SortedByCoordinate` followed by `htseq-count -r pos -s no Aligned.sortedByCoord.out.bam`

Because all numbers agree, this isn't very useful to expose bugs in htseq and/or STAR. Both software appear to work as designed. So I propose to close this issue and I will also close the one in the htseq repo.

**Comment by alexdobin** [comment] 2020-12-28 20:02
Hi Fabio,

thanks for the thorough tests and the confirmation that htseq-count and STAR produce identical results in various scenarios.
I concur that we can close this issue.

Cheers
Alex

**Closed by alexdobin** 2020-12-28 20:02 UTC
Labels: issue: results
